import { useState, useEffect } from "react"
import test from "../media/character-images/medium-mode/amaterasu.png"
import * as imageModule from "../imageExports"
const CurrentObjectives = () => {
    //the indexes of the character image consts are sorted to match the order of the CharacterDropdown list in PhotoTagging so that the same index in that component can be used to delete the nodes generated by populateImages to create a responsive HUD for the user
    const easyCharacterImages = [imageModule.guile, imageModule.ironman, imageModule.leo, imageModule.ryu, imageModule.scorpion, imageModule.venom];
    const mediumCharacterImages = [imageModule.amaterasu, imageModule.cloud, imageModule.commanderShephard, imageModule.dukeNukem, imageModule.jakDaxter, imageModule.slyCooper];
    const hardCharacterImages = [imageModule.batrider, imageModule.darkSeer, imageModule.luna, imageModule.magnus, imageModule.medusa, imageModule.naturesProphet, imageModule.phantomAssassin, imageModule.sven, imageModule.tinker];
    const [deleteImageIndex, setDeleteImageIndex] = useState(sessionStorage.getItem("deleteImageIndex"));
    let jsonCharacterList = sessionStorage.getItem("characterList");
    let difficulty = sessionStorage.getItem("difficulty")
    let parsedList = JSON.parse(jsonCharacterList);
    let characterKeys = Object.keys(parsedList);

    //TODO take the newly added image id's and associate them somehow with a truthy character dropdown list selection so that the image transitions out of the image list
    const populateImages = () => {
        if (difficulty === "easy") {
            return easyCharacterImages.map((element, index) => <img className={"current-objective-images"} key={`key-${index}`} src={element}></img>)
        } else if (difficulty === "medium") {
            return mediumCharacterImages.map((element, index) => <img className={"current-objective-images"} key={`key-${index}`} src={element}></img>)
        } else if (difficulty === "hard") {
            return hardCharacterImages.map((element, index) => <img className={"current-objective-images"} key={`key-${index}`} src={element}></img>)
        }
    }

    useEffect(() => {
        let objectiveImagesNode = document.getElementById("current-objectives");
        console.log(document.getElementById("current-objectives"))
        console.log(deleteImageIndex)

        //check for null as a string since storage method objects are always strings
        if (deleteImageIndex != "null") {
            objectiveImagesNode.removeChild(objectiveImagesNode.childNodes[Number(deleteImageIndex)]);
            console.log('deleted node')
            //insures no further deletions occur following checkSelection() calls in PhotoTagging component
            sessionStorage.setItem("deleteImageIndex", "null")
        }
        setDeleteImageIndex(sessionStorage.getItem("deleteImageIndex"))
    });
    return (
        <div id="current-objectives">
            {
                populateImages()
            }
        </div>
    );
}

export { CurrentObjectives }